name: CI

on:
  push:
    branches: [ master ]
 


jobs:

  build:
    
    runs-on: ubuntu-latest


    steps:
  
    - uses: actions/checkout@v2
  
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
      
    - name: Install dependencies
      run: yarn
      
    - name: Run Build
      run: yarn build
      
    - name: Copiar código para Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ sercrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app/GoBarberV2"
